### Testing API Call


### GET request to main route
GET http://localhost:8000/


### POST New User
POST http://localhost:8000/api/v1/users/
Content-Type: application/json

{
  "name": "Subodh",
  "password": "11111",
  "email": "subodh2adhikari@gmail.com"
}