### Testing API Call


### GET request to main route
GET http://localhost:8000/

### GET user info from the token
GET http://localhost:8000/api/v1/users/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzQyOTg3MzQxLCJleHAiOjE3NDM1OTIxNDF9.dDMdqhVmFXURkQ-T0bVt6edYVtC_93egTEFpjbcoR7s


### POST New User
POST http://localhost:8000/api/v1/users/
Content-Type: application/json

{
  "name": "Donkey",
  "email": "donk1210066@gmail.com",
  "password": "11111"
}

### POST Login
POST http://localhost:8000/api/v1/users/login
Content-Type: application/json


{
  "email": "a@gmail.com",
  "password": "a"
}

### Transactions: all private routes

### Post new transaction

POST http://localhost:8000/api/v1/transactions/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzQyOTg3MzQxLCJleHAiOjE3NDM1OTIxNDF9.dDMdqhVmFXURkQ-T0bVt6edYVtC_93egTEFpjbcoR7s


{
  "type": "income",
  "title": "salary",
  "amount": "55",
  "date": "2025-02-14"
}


### GET all transactions for a specific user
GET http://localhost:8000/api/v1/transactions/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzQyOTg3MzQxLCJleHAiOjE3NDM1OTIxNDF9.dDMdqhVmFXURkQ-T0bVt6edYVtC_93egTEFpjbcoR7s

### DELETE transactions for a specific user
DELETE http://localhost:8000/api/v1/transactions/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzQyOTg3MzQxLCJleHAiOjE3NDM1OTIxNDF9.dDMdqhVmFXURkQ-T0bVt6edYVtC_93egTEFpjbcoR7s

["67e81a18e2b2614d8b2e8c9c","67e8208041bf698d7014c171"]